Add tab header to sit above tab settings and tab content
jadu/pulsar pull request #1297
Opened 2020-08-24 14:19 UTC by Stanton

Required for XFP Data Retention UI, adds a new block which sits above the tab sidebar & content, but below the actions bar.

Example:

```twig
{% block tab_header %}

  {{
      html.panel({
          'title': '',
          'body': form.toggle_switch({
            'label': 'Clear user data on submission'
          }) ~ '<p>If enabled, any system-wide data retention policies will not apply to this form. Instead, you’ll need to define new policies specific to this form.
Choosing to override global policies and not defining any form specific policies will mean form data is never removed. This is not recommended.</p>',
      })
  }}

{% endblock tab_header %}

{% block tab_settings %}

    <div class="settings-section settings-section--primary">
        <h2 class="settings-section__heading">Settings</h2>

        {{
          form.toggle_switch({
            'label': 'Clear user data on submission'
          })
        }}

        <p>Enabling this option will prevent all user-submitted data from being saved on this website. You must therefore ensure that at least one rule has been configured, in order to export the data to a third party system instead (e.g Jadu CXM).</p>
        <p>This option will also prevent users downloading a PDF of their submission. Should you wish, the user's email receipt can instead be configured to have this PDF attached.</p>
    </div>

{% endblock tab_settings %}
```

2020-09-04 11:06 UTC, Stanton commented
@james-manley Can you provide some detail about when you need this change, please? Presuming as part of `11.0.0beta2` ?

2020-09-10 10:11 UTC, jamesjacobs requested changes

2020-09-10 10:11 UTC, jamesjacobs commented on stylesheets/_layout.settings.scss
>          display: flex;
I know this hasn't changed in this PR but we have two `display`'s here

2020-09-10 10:11 UTC, jamesjacobs commented on stylesheets/_layout.tabs.scss
> +    flex-basis: 100%;
Feel like this should be set within `_layout.settings.scss` as that's the only place `.tab__header` would be within an element with `display: flex` (other layouts don't use flex), perhaps nested within the the rule block that contains the `flex-wrap` change above.

2020-09-10 10:11 UTC, jamesjacobs commented on views/lexicon/patterns/tab-header/table.html.twig
> +    <p>tab header goes here</p>
Could we add this to the settings panel too, with it having it's own settings specific flex styling. Would be helpful for future layout testing.

2020-09-10 10:34 UTC, jamesjacobs approved these changes
Approved with a minor point.

2020-09-10 10:34 UTC, jamesjacobs commented on stylesheets/_layout.tabs.scss
> +    width: 100%;
I'd move this up with flex-basis as we know it's always going to be a div and I suspect that the width is only needed when flexing?

Unless there's another reason why we need to specify it?

2020-09-10 12:41 UTC, merged